//
// Created by ilcondor on 16/04/24.
//

#ifndef CHATROOM_BROADCASTUSERDISCONNECTEDMESSAGE_H
#define CHATROOM_BROADCASTUSERDISCONNECTEDMESSAGE_H

#endif //CHATROOM_BROADCASTUSERDISCONNECTEDMESSAGE_H
